### ISSUE TITLE
Question - Mining Level

### ISSUE THREAD

**Issue by TheUntamed** [Fuzss/materialmaster#3]
The harvest level of a tool can be changed, can the mining level of a block also be changed?

And i'm not sure if I understood the format for changing a tools harvest level. What is path and would that be an entry for the list in the configs if path would be replaced correctly?:

`minecraft:stone_pickaxe:<path>,3`

**Comment by Fuzss** [comment]
This mod is not intended for modifying blocks.

For config entries:
`<namespace>:<path>,<value>` -> `minecraft:stone_pickaxe,3`
Multiple entries:
`"Harvest Level List" = ["minecraft:stone_pickaxe,3", "minecraft:iron_pickaxe,4"]`
