### ISSUE TITLE
Unifying and Overriding Attributes

### ISSUE THREAD

**Issue by TrueDakkon** [Fuzss/materialmaster#5]
I really enjoy this mod and what it allows modpack devs to do, but I have some qualms with it. First is more of a nitpick, but when making any changes to the attributes on an item I end up seeing the same attribute listed twice, one is the original and one is the additional one the mod adds. I think it would look a lot better if that weren't the case and it just unified it all into one attribute at the end. 
The other issue I have is that the mod doesn't allow for overriding of attributes, at least not when it comes to armor/weapons. The most it allows for overriding is the durability and I was wondering why the rest can't be overridden just the same? It would allow for even more control over the equipment and I feel would be generally a welcome addition to the mod. I'm not sure of the inner workings of the mod, but I know to some degree that these attributes can be overridden in base Minecraft with commands, so I find it a bit puzzling that we can't do the same with the mod. 
Thanks for the great mod, and I wish you the best!

**Comment by TrueDakkon** [comment]
One other thing I would like to suggest would be that fall damage/distance to take damage be tied to the players gravity. That way when I have players that are able to jump like three to four blocks they aren't taking fall damage from jumping alone. I think a system where for every one block higher you can jump, you can fall an extra one or two would be nice.

**Comment by Fuzss** [comment]
Mod is discontinued now, as an alternative I recommend this one: https://www.curseforge.com/minecraft/mc-mods/property-modifier
