### ISSUE TITLE
Attributes not Being Applied on Starting

### ISSUE THREAD

**Issue by TrueDakkon** [Fuzss/materialmaster#6]
When starting up the game I have noticed that upon first start that the attributes aren't being applied. This means that in order to apply them that I need to reload the configs for the game. This isn't so bad when developing a modpack, but when it comes to sending one out it could lead to some issues. Most players will not realize that they need to reload to apply the custom armor attributes and will proceed to play without them. If it is possible, I think there needs to be a method added to auto apply the attributes on launch as to not cause any issues.

**Comment by danielmartin0** [comment]
Same issue here. v1.3.1-1.15.2. The error is fatal because users will proceed to desync from the multiplayer server when they possess the item.

**Comment by danielmartin0** [comment]
Fixed by downgrading to v1.1.3.

**Comment by Fuzss** [comment]
Mod is discontinued now, as an alternative I recommend this one: https://www.curseforge.com/minecraft/mc-mods/property-modifier
